---
# defaults file for manage_hub_collections
hub_remote_repos:
  - name: rh-certified
    url: https://console.redhat.com/api/automation-hub/content/published/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    token: "{{ hub_redhat_token }}"
  - name: community
    url: https://galaxy.ansible.com/api/
    requirements: []
  - name: validated
    url: https://console.redhat.com/api/automation-hub/content/validated/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    token: "{{ hub_redhat_token }}"
